name: Project Build & Test
on:
  push:
  workflow_dispatch: # allow manual trigger

jobs:
  uv-build:
    name: python
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/pkmnrlarena/ci-image:latest  
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.17"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the dependencies
        run: uv sync --locked --all-extras --dev

      - name: Install the project
        run: uv pip install . -v

      - name: Run tests
        run: uv run pytest tests/*
